version: '3.6'

services:
  web:
    build: src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    env_file:
      - src/.env
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8080:8080